services:
  soabus:
    image: jrgiadach/soabus:latest
    ports: ["5000:5000"]
    restart: unless-stopped

  app:
    build: .
    depends_on: [soabus]
    env_file: [.env]
    command: ["python","-m","Sistema_Ticket_Soa.main"]
    stdin_open: true
    tty: true